# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Pavel/workspace/Jupiter/apps/PyGameDesigner/res/NodeSettings.ui'
#
# Created: Tue May 19 22:47:57 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_NodeSettings(object):
    def setupUi(self, NodeSettings):
        NodeSettings.setObjectName("NodeSettings")
        NodeSettings.resize(524, 178)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/stationery.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        NodeSettings.setWindowIcon(icon)
        self.verticalLayout_8 = QtGui.QVBoxLayout(NodeSettings)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.visible = QtGui.QCheckBox(NodeSettings)
        self.visible.setObjectName("visible")
        self.verticalLayout_6.addWidget(self.visible)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.positionGroupBox = QtGui.QGroupBox(NodeSettings)
        self.positionGroupBox.setObjectName("positionGroupBox")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.positionGroupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.labelPositionX = QtGui.QLabel(self.positionGroupBox)
        self.labelPositionX.setObjectName("labelPositionX")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelPositionX)
        self.xPosition = QtGui.QDoubleSpinBox(self.positionGroupBox)
        self.xPosition.setMinimum(-9999.0)
        self.xPosition.setMaximum(9999.0)
        self.xPosition.setSingleStep(0.01)
        self.xPosition.setObjectName("xPosition")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.xPosition)
        self.labelPositionY = QtGui.QLabel(self.positionGroupBox)
        self.labelPositionY.setObjectName("labelPositionY")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelPositionY)
        self.yPosition = QtGui.QDoubleSpinBox(self.positionGroupBox)
        self.yPosition.setMinimum(-9999.0)
        self.yPosition.setMaximum(9999.0)
        self.yPosition.setSingleStep(0.01)
        self.yPosition.setObjectName("yPosition")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.yPosition)
        self.labelPositionZ = QtGui.QLabel(self.positionGroupBox)
        self.labelPositionZ.setObjectName("labelPositionZ")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelPositionZ)
        self.zPosition = QtGui.QDoubleSpinBox(self.positionGroupBox)
        self.zPosition.setMinimum(-9999.0)
        self.zPosition.setMaximum(9999.0)
        self.zPosition.setSingleStep(0.01)
        self.zPosition.setObjectName("zPosition")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.zPosition)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.horizontalLayout.addWidget(self.positionGroupBox)
        self.scaleGroupBox = QtGui.QGroupBox(NodeSettings)
        self.scaleGroupBox.setObjectName("scaleGroupBox")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.scaleGroupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.labelScaleX = QtGui.QLabel(self.scaleGroupBox)
        self.labelScaleX.setObjectName("labelScaleX")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelScaleX)
        self.xScale = QtGui.QDoubleSpinBox(self.scaleGroupBox)
        self.xScale.setMinimum(-9999.0)
        self.xScale.setMaximum(9999.0)
        self.xScale.setSingleStep(0.01)
        self.xScale.setObjectName("xScale")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.xScale)
        self.labelScaleY = QtGui.QLabel(self.scaleGroupBox)
        self.labelScaleY.setObjectName("labelScaleY")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelScaleY)
        self.yScale = QtGui.QDoubleSpinBox(self.scaleGroupBox)
        self.yScale.setMinimum(-9999.0)
        self.yScale.setMaximum(9999.0)
        self.yScale.setSingleStep(0.01)
        self.yScale.setObjectName("yScale")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.yScale)
        self.labelScaleZ = QtGui.QLabel(self.scaleGroupBox)
        self.labelScaleZ.setObjectName("labelScaleZ")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelScaleZ)
        self.zScale = QtGui.QDoubleSpinBox(self.scaleGroupBox)
        self.zScale.setMinimum(-9999.0)
        self.zScale.setMaximum(9999.0)
        self.zScale.setSingleStep(0.01)
        self.zScale.setObjectName("zScale")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.zScale)
        self.verticalLayout_4.addLayout(self.formLayout_2)
        self.horizontalLayout.addWidget(self.scaleGroupBox)
        self.rotationGroupBox = QtGui.QGroupBox(NodeSettings)
        self.rotationGroupBox.setObjectName("rotationGroupBox")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.rotationGroupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.rotationXLabel = QtGui.QLabel(self.rotationGroupBox)
        self.rotationXLabel.setObjectName("rotationXLabel")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.rotationXLabel)
        self.rotationX = QtGui.QDoubleSpinBox(self.rotationGroupBox)
        self.rotationX.setDecimals(4)
        self.rotationX.setMinimum(0.0)
        self.rotationX.setMaximum(1.0)
        self.rotationX.setSingleStep(0.001)
        self.rotationX.setObjectName("rotationX")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.rotationX)
        self.rotationYLabel = QtGui.QLabel(self.rotationGroupBox)
        self.rotationYLabel.setObjectName("rotationYLabel")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.rotationYLabel)
        self.rotationY = QtGui.QDoubleSpinBox(self.rotationGroupBox)
        self.rotationY.setDecimals(4)
        self.rotationY.setMinimum(0.0)
        self.rotationY.setMaximum(1.0)
        self.rotationY.setSingleStep(0.001)
        self.rotationY.setProperty("value", 0.0)
        self.rotationY.setObjectName("rotationY")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.rotationY)
        self.rotationZLabel = QtGui.QLabel(self.rotationGroupBox)
        self.rotationZLabel.setObjectName("rotationZLabel")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.rotationZLabel)
        self.rotationZ = QtGui.QDoubleSpinBox(self.rotationGroupBox)
        self.rotationZ.setDecimals(4)
        self.rotationZ.setMaximum(1.0)
        self.rotationZ.setSingleStep(0.001)
        self.rotationZ.setObjectName("rotationZ")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.rotationZ)
        self.rotationAngleLabel = QtGui.QLabel(self.rotationGroupBox)
        self.rotationAngleLabel.setObjectName("rotationAngleLabel")
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.rotationAngleLabel)
        self.rotationAngle = QtGui.QDoubleSpinBox(self.rotationGroupBox)
        self.rotationAngle.setMinimum(-9999.0)
        self.rotationAngle.setMaximum(9999.0)
        self.rotationAngle.setSingleStep(0.01)
        self.rotationAngle.setObjectName("rotationAngle")
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.rotationAngle)
        self.verticalLayout_7.addLayout(self.formLayout_3)
        self.horizontalLayout.addWidget(self.rotationGroupBox)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.nameGroupBox = QtGui.QGroupBox(NodeSettings)
        self.nameGroupBox.setObjectName("nameGroupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.nameGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.name = QtGui.QLineEdit(self.nameGroupBox)
        self.name.setObjectName("name")
        self.verticalLayout.addWidget(self.name)
        self.verticalLayout_5.addWidget(self.nameGroupBox)
        self.tagGroupBox = QtGui.QGroupBox(NodeSettings)
        self.tagGroupBox.setObjectName("tagGroupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tagGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tag = QtGui.QSpinBox(self.tagGroupBox)
        self.tag.setMinimum(-1)
        self.tag.setMaximum(9999)
        self.tag.setObjectName("tag")
        self.verticalLayout_2.addWidget(self.tag)
        self.verticalLayout_5.addWidget(self.tagGroupBox)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)

        self.retranslateUi(NodeSettings)
        QtCore.QMetaObject.connectSlotsByName(NodeSettings)

    def retranslateUi(self, NodeSettings):
        NodeSettings.setWindowTitle(QtGui.QApplication.translate("NodeSettings", "Настройки узла", None, QtGui.QApplication.UnicodeUTF8))
        self.visible.setText(QtGui.QApplication.translate("NodeSettings", "Видимость", None, QtGui.QApplication.UnicodeUTF8))
        self.positionGroupBox.setTitle(QtGui.QApplication.translate("NodeSettings", "Позиция", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPositionX.setText(QtGui.QApplication.translate("NodeSettings", "X: ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPositionY.setText(QtGui.QApplication.translate("NodeSettings", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPositionZ.setText(QtGui.QApplication.translate("NodeSettings", "Z:", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleGroupBox.setTitle(QtGui.QApplication.translate("NodeSettings", "Масштаб", None, QtGui.QApplication.UnicodeUTF8))
        self.labelScaleX.setText(QtGui.QApplication.translate("NodeSettings", "X: ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelScaleY.setText(QtGui.QApplication.translate("NodeSettings", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelScaleZ.setText(QtGui.QApplication.translate("NodeSettings", "Z:", None, QtGui.QApplication.UnicodeUTF8))
        self.rotationGroupBox.setTitle(QtGui.QApplication.translate("NodeSettings", "Поворот", None, QtGui.QApplication.UnicodeUTF8))
        self.rotationXLabel.setText(QtGui.QApplication.translate("NodeSettings", "X: ", None, QtGui.QApplication.UnicodeUTF8))
        self.rotationYLabel.setText(QtGui.QApplication.translate("NodeSettings", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.rotationZLabel.setText(QtGui.QApplication.translate("NodeSettings", "Z:", None, QtGui.QApplication.UnicodeUTF8))
        self.rotationAngleLabel.setText(QtGui.QApplication.translate("NodeSettings", "Угол", None, QtGui.QApplication.UnicodeUTF8))
        self.nameGroupBox.setTitle(QtGui.QApplication.translate("NodeSettings", "Имя узла", None, QtGui.QApplication.UnicodeUTF8))
        self.tagGroupBox.setTitle(QtGui.QApplication.translate("NodeSettings", "Тэг", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
