language: cpp
compiler:
    - gcc
before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq libegl1-mesa-dev libxmu6 libxmu-dev zlib1g-dev libpcre3-dev p7zip-full libxi-dev libreadline-dev cmake
script: mkdir build && cd build && cmake .. && cmake --build .
