language: cpp
compiler:
    - gcc
before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq libegl1-mesa-dev libxmu6 libxmu-dev zlib1g-dev libpcre3-dev p7zip-full libxi-dev libreadline-dev
install:
    - wget https://cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz
    - tar xf cmake-3.3.2-Linux-x86_64.tar.gz
    - export PATH=$PATH:cmake-3.3.2-Linux-x86_64/bin

script: cmake --build .
